#
# Copyright (c) 2014, Juniper Networks, Inc.
# All rights reserved.
#
VPATH = $(TOPDIR)

LIB = libpostacx_icrt.a

COBJS = memory.o post.o tests.o usb.o nand.o cpu.o watchdog.o ether.o \
	syspld.o nor.o secureboot.o

include $(ALTSRCTREE)/post/acx_icrt/rules.mk
