/* Please do not add platform specific #if defines in this file.
 * loader uses this list and adding #ifdefs will put them
 * out of sync.
 */
EXPORT_FUNC(get_version)
EXPORT_FUNC(getc)
EXPORT_FUNC(tstc)
EXPORT_FUNC(putc)
EXPORT_FUNC(puts)
EXPORT_FUNC(printf)
EXPORT_FUNC(install_hdlr)
EXPORT_FUNC(free_hdlr)
EXPORT_FUNC(malloc)
EXPORT_FUNC(free)
EXPORT_FUNC(udelay)
EXPORT_FUNC(get_timer)
EXPORT_FUNC(vprintf)
EXPORT_FUNC(do_reset)
EXPORT_FUNC(getenv)
EXPORT_FUNC(setenv)
EXPORT_FUNC(simple_strtoul)
EXPORT_FUNC(i2c_write)
EXPORT_FUNC(i2c_read)
EXPORT_FUNC(eth_init)
EXPORT_FUNC(eth_halt)
EXPORT_FUNC(eth_send)
EXPORT_FUNC(eth_receive)
EXPORT_FUNC(disk_scan)
EXPORT_FUNC(disk_read)
EXPORT_FUNC(disk_write)
EXPORT_FUNC(lcd_printf)
EXPORT_FUNC(saveenv)
EXPORT_FUNC(i2c_read8)
EXPORT_FUNC(i2c_read16)
EXPORT_FUNC(i2c_write8)
EXPORT_FUNC(i2c_write16)
EXPORT_FUNC(octeon_twsi_write_max)
EXPORT_FUNC(octeon_twsi_read_max)
EXPORT_FUNC(i2c_read8_generic)
EXPORT_FUNC(i2c_write8_generic)
EXPORT_FUNC(i2c_switch_programming)
EXPORT_FUNC(cvmx_pcie_mem_read32)
EXPORT_FUNC(cvmx_pcie_mem_write32)
EXPORT_FUNC(cvmx_pcie_config_read32)
EXPORT_FUNC(cvmx_pcie_config_write32)
EXPORT_FUNC(eth_set_current)
EXPORT_FUNC(cvmx_pcie_config_regex)
EXPORT_FUNC(get_next_bootdev)
EXPORT_FUNC(set_next_bootdev)
EXPORT_FUNC(show_bootdev_list)
EXPORT_FUNC(reload_watchdog)
#if defined(CONFIG_EX82XX) || defined(CONFIG_EX3242) || \
    defined(CONFIG_EX45XX) || defined(CONFIG_EX2200) || defined(CONFIG_EX3300)
EXPORT_FUNC(disable_hw_access)
#endif
#if defined(CONFIG_JSRXNLE) || defined(CONFIG_MAG8600)
EXPORT_FUNC(cpld_read)
EXPORT_FUNC(cpld_write)
EXPORT_FUNC(uart_init)
EXPORT_FUNC(uart_getc)
EXPORT_FUNC(uart_putc)
EXPORT_FUNC(octeon_pci_read_io)
EXPORT_FUNC(octeon_pci_write_io)
EXPORT_FUNC(octeon_read_config)
EXPORT_FUNC(init_octeon_pci)
EXPORT_FUNC(octeon_gpio_ext_cfg_output)
EXPORT_FUNC(octeon_gpio_set)
EXPORT_FUNC(limit_l2_ways)
EXPORT_FUNC(nand_phys_page_read)
#endif
/* The following list of functions are used by a mini shell application.
 * These need to be cleaned up. These are not used by the loader.
 */
#ifdef CONFIG_FX
EXPORT_FUNC(pci_find_devices)
EXPORT_FUNC(pci_read_config_byte)
EXPORT_FUNC(pci_write_config_byte)
EXPORT_FUNC(pci_read_config_word)
EXPORT_FUNC(pci_write_config_word)
EXPORT_FUNC(pci_read_config_dword)
EXPORT_FUNC(pci_write_config_dword)
#endif /* CONFIG_FX */
EXPORT_FUNC(get_tbclk)
#ifdef CONFIG_MARVELL
EXPORT_FUNC(realloc)
EXPORT_FUNC(calloc)
EXPORT_FUNC(memalign)
EXPORT_FUNC(mvGetRtcSec)
#endif
#if defined(CONFIG_EX2200)
EXPORT_FUNC(syspld_watchdog_disable)
EXPORT_FUNC(syspld_watchdog_enable)
EXPORT_FUNC(syspld_watchdog_petting)
#endif
#if defined(CONFIG_RPS200)
EXPORT_FUNC(rps_reset)
EXPORT_FUNC(i2c_cpld_reset)
EXPORT_FUNC(i2c_reset)
EXPORT_FUNC(i2c_slave_write_wait)
EXPORT_FUNC(i2c_slave_read_wait)
EXPORT_FUNC(rps_nand_read)
EXPORT_FUNC(rps_nand_write)
EXPORT_FUNC(rps_nand_block_isbad)
EXPORT_FUNC(rps_nand_erase)
EXPORT_FUNC(watchdog_init)
EXPORT_FUNC(watchdog_disable)
EXPORT_FUNC(watchdog_enable)
EXPORT_FUNC(watchdog_reset)
EXPORT_FUNC(upgrade_rps_image)
#endif

