/*
 * fortius_js_defs_struct.h -- JS Word definitions for fortius_syspld
 *
 * Generated by JSPEC 1.12.9.  Do not edit!
 *
 * Copyright (c) 2012-2013, Juniper Networks, Inc.
 * All rights reserved.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-2.0.html>.
 *
 * $Id: struct_h.c,v 1.12.9 Mon Mar  5 11:24:15 2012 prithiviraj Exp $
 */

#ifndef __JSWORD_TYPEDEF__
#define __JSWORD_TYPEDEF__
typedef struct {
    volatile u_int32_t word[3]; 
} js_word96_t;

typedef struct {
    volatile u_int32_t word[4]; 
} js_word128_t;

typedef struct {
    volatile u_int32_t word[5]; 
} js_word160_t;

typedef struct {
    volatile u_int32_t word[6]; 
} js_word192_t;

typedef struct {
    volatile u_int32_t word[7]; 
} js_word224_t;

typedef struct {
    volatile u_int32_t word[8]; 
} js_word256_t;

typedef struct {
    volatile u_int32_t word[9]; 
} js_word288_t;

typedef struct {
    volatile u_int32_t word[10]; 
} js_word320_t;

typedef struct {
    volatile u_int32_t word[11]; 
} js_word352_t;

typedef struct {
    volatile u_int32_t word[12]; 
} js_word384_t;

typedef struct {
    volatile u_int32_t word[13]; 
} js_word416_t;

typedef struct {
    volatile u_int32_t word[14]; 
} js_word448_t;

typedef struct {
    volatile u_int32_t word[15]; 
} js_word480_t;

typedef struct {
    volatile u_int32_t word[16]; 
} js_word512_t;

typedef struct {
    volatile u_int32_t word[17]; 
} js_word544_t;

typedef struct {
    volatile u_int32_t word[18]; 
} js_word576_t;

typedef struct {
    volatile u_int32_t word[19]; 
} js_word608_t;

typedef struct {
    volatile u_int32_t word[20]; 
} js_word640_t;

typedef struct {
    struct {
        union {
             js_word96_t word96;
             volatile u_int32_t word[3];
        };
    };
    unsigned : 32;
} js_word96_padded_t;

typedef struct {
    struct {
        union {
             js_word128_t word128;
             volatile u_int32_t word[4];
        };
    };
} js_word128_padded_t;

typedef struct {
    struct {
        union {
             js_word160_t word160;
             volatile u_int32_t word[5];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word160_padded_t;

typedef struct {
    struct {
        union {
             js_word192_t word192;
             volatile u_int32_t word[6];
        };
    };
    unsigned : 32;
    unsigned : 32;
} js_word192_padded_t;

typedef struct {
    struct {
        union {
             js_word224_t word224;
             volatile u_int32_t word[7];
        };
    };
    unsigned : 32;
} js_word224_padded_t;

typedef struct {
    struct {
        union {
             js_word256_t word256;
             volatile u_int32_t word[8];
        };
    };
} js_word256_padded_t;

typedef struct {
    struct {
        union {
             js_word288_t word288;
             volatile u_int32_t word[9];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word288_padded_t;

typedef struct {
    struct {
        union {
             js_word320_t word320;
             volatile u_int32_t word[10];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word320_padded_t;

typedef struct {
    struct {
        union {
             js_word352_t word352;
             volatile u_int32_t word[11];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word352_padded_t;

typedef struct {
    struct {
        union {
             js_word384_t word384;
             volatile u_int32_t word[12];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word384_padded_t;

typedef struct {
    struct {
        union {
             js_word416_t word416;
             volatile u_int32_t word[13];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word416_padded_t;

typedef struct {
    struct {
        union {
             js_word448_t word448;
             volatile u_int32_t word[14];
        };
    };
    unsigned : 32;
    unsigned : 32;
} js_word448_padded_t;

typedef struct {
    struct {
        union {
             js_word480_t word480;
             volatile u_int32_t word[15];
        };
    };
    unsigned : 32;
} js_word480_padded_t;

typedef struct {
    struct {
        union {
             js_word512_t word512;
             volatile u_int32_t word[16];
        };
    };
} js_word512_padded_t;

typedef struct {
    struct {
        union {
             js_word544_t word544;
             volatile u_int32_t word[17];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word544_padded_t;

typedef struct {
    struct {
        union {
             js_word576_t word576;
             volatile u_int32_t word[18];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word576_padded_t;

typedef struct {
    struct {
        union {
             js_word608_t word608;
             volatile u_int32_t word[19];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word608_padded_t;

typedef struct {
    struct {
        union {
             js_word640_t word640;
             volatile u_int32_t word[20];
        };
    };
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
    unsigned : 32;
} js_word640_padded_t;


#endif 

